name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t rbdb-test .

    - name: Run tests
      run: docker run --rm rbdb-test swift test

    - name: Check code formatting
      run: docker run --rm rbdb-test swift format lint -s --recursive .